apiVersion: landscape.config.gardener.cloud/v1alpha1
kind: LandscapeKitConfiguration
# ocm:
#   repositories:
#   - <repo-url>
#   rootComponent:
#     name: <component-name>
#     version: <component-version>
#   originalRefs: true
# git:
#   url: https://github.com/<org>/<repo>
#   ref:
#     branch: <branch-name>
#   paths:
#     base: ./base
#     landscape: ./
# components:
#   exclude:
#   - component-name
# versionConfig:
#   componentsVectorFile: ./versions.yaml
