apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: virtual-garden-access-flux
  namespace: garden
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: {{ .landscapeComponentPath }}
  prune: true
  dependsOn:
  - name: garden
    namespace: garden
  interval: 30m
  timeout: 5m
  retryInterval: 10m
  wait: true
