apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: extension-networking-cilium
  namespace: garden
spec:
  interval: 30m
  path: {{ .landscapeComponentPath }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
  - name: gardener-operator
    namespace: garden
