apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garden-config
  namespace: garden
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: {{ .landscapeComponentPath }}
  prune: true
  dependsOn:
  - name: virtual-garden-access-flux
    namespace: garden
  kubeConfig:
    secretRef:
      name: shoot-access-virtual-garden-flux
      key: kubeconfig
  interval: 30m
  timeout: 5m
  retryInterval: 10m
  wait: true
  healthCheckExprs:
  - apiVersion: core.gardener.cloud/v1beta1
    kind: Project
    current: "status.phase == 'Ready'"
