name: Release

on:
  workflow_dispatch:
    inputs:
      next-version:
        type: choice
        options:
        - bump-patch
        description: 'Select the type of version bump for the next release.'

jobs:
  build:
    if: ${{ github.repository == 'gardener/gardener-landscape-kit' && startsWith(github.ref, 'refs/heads/release-v') }}
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: write
      id-token: write
      packages: write
    with:
      mode: release

  release-to-github-and-bump:
    if: ${{ github.repository == 'gardener/gardener-landscape-kit' && startsWith(github.ref, 'refs/heads/release-v') }}
    uses: gardener/cc-utils/.github/workflows/release.yaml@master
    needs:
      - build
    secrets: inherit
    permissions:
      contents: write
      id-token: write
      packages: write
    with:
      release-commit-target: branch
      next-version: ${{ inputs.next-version }}
      next-version-callback-action-path:
      # slack-channel-id:
      assets: |
        - name: gardener-landscape-kit-darwin-amd64
          type: ocm-resource
          id:
            name: gardener-landscape-kit
            os: darwin
            architecture: amd64
        - name: gardener-landscape-kit-linux-amd64
          type: ocm-resource
          id:
            name: gardener-landscape-kit
            os: linux
            architecture: amd64
        - name: gardener-landscape-kit-windows-amd64
          type: ocm-resource
          id:
            name: gardener-landscape-kit
            os: windows
            architecture: amd64
